steps:
  - name: 'python:3.13'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        mypy . && pytest
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/pdf-assistant:$BUILD_ID
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/pdf-assistant:$BUILD_ID
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - api
      - --image
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/pdf-assistant:$BUILD_ID
      - --add-cloudsql-instances
      - $PROJECT_ID:asia-northeast1:pdf-assistant
      - --region
      - asia-northeast1
      - --cpu
      - 1000m
      - --memory
      - 512Mi
      - --port
      - "8080"
      - --platform
      - managed
      - --no-allow-unauthenticated
      - --service-account
      - cloud-run-sa@$PROJECT_ID.iam.gserviceaccount.com
      - --set-env-vars
      - PROJECT_ID=$PROJECT_ID
      - --ingress
      - all
      - --command
      - "sh"
      - --args
      - "-c,python -m entrypoint.api"
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - jobs
      - deploy
      - clean-openai-assistant
      - --image
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/pdf-assistant:$BUILD_ID
      - --set-cloudsql-instances
      - $PROJECT_ID:asia-northeast1:pdf-assistant
      - --region
      - asia-northeast1
      - --cpu
      - 1000m
      - --memory
      - 512Mi
      - --service-account
      - cloud-run-sa@$PROJECT_ID.iam.gserviceaccount.com
      - --set-env-vars
      - PROJECT_ID=$PROJECT_ID
      - --max-retries
      - "0"
      - --parallelism
      - "1"
      - --tasks
      - "1"
      - --command
      - "sh"
      - --args
      - "-c,python -m entrypoint.clean_openai_assistant"
timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY