swagger: "2.0"
info:
  title: Hello World API
  description: This API returns a simple "hello, world" message.
  version: "1.0.0"
host: "api-gateway-app-pdf-assistant.run.app"
schemes:
  - "https"
basePath: "/hello"
paths:
  /hello:
    post:
      summary: Get a hello message
      description: Returns a simple hello world message in JSON format.
      operationId: postHello
      x-google-backend:
        address: { https://pdf-assistant-445201-794862978184.asia-northeast1.run.app }
        path_translation: { APPEND_PATH_TO_ADDRESS }
      produces:
        - "application/json"
      responses:
        200:
          description: A JSON object containing a hello world message.
          schema:
            type: object
            properties:
              hello:
                type: string
            required:
              - hello
          examples:
            application/json:
              hello: "world"