swagger: "2.0"
info:
  title: PDF Assistant API
  version: "1.0.0"
host: "api-gateway-7nwm7l18.an.gateway.dev"
schemes:
  - "https"
produces:
  - "application/json"
basePath: "/"

x-google-backend:
  address: https://pdf-assistant-api-600587365436.asia-northeast1.run.app
  path_translation: APPEND_PATH_TO_ADDRESS

securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://dev-im6sd3gmyj703h6n.us.auth0.com/"
    x-google-jwks_uri: "https://dev-im6sd3gmyj703h6n.us.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://api-gateway-7nwm7l18.an.gateway.dev"
security:
  - auth0_jwk: [ ]

paths:
  /me:
    get:
      operationId: me
      responses:
        200:
          description: return login user
          schema:
            $ref: "#/definitions/User"
  /users:
    post:
      operationId: createUser
      parameters:
        - name: name
          in: formData
          required: true
          type: string
      responses:
        200:
          description: return created user or exist user
          schema:
            $ref: "#/definitions/User"
    put:
      operationId: updateUser
      parameters:
        - name: name
          in: formData
          required: true
          type: string
      responses:
        200:
          description: return updated user
          schema:
            $ref: "#/definitions/User"
  /documents:
    post:
      operationId: createDocument
      parameters:
        - name: name
          in: formData
          required: true
          type: string
        - name: description
          in: formData
          required: true
          type: string
        - name: gs_key
          in: formData
          required: true
          type: string
      responses:
        200:
          description: return created document
          schema:
            $ref: "#/definitions/Document"
  /documents/{id}:
    get:
      operationId: getDocument
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: return document
          schema:
            $ref: "#/definitions/Document"
    put:
      operationId: updateDocument
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: name
          in: formData
          required: true
          type: string
        - name: description
          in: formData
          required: true
          type: string
      responses:
        200:
          description: return updated document
          schema:
            $ref: "#/definitions/Document"
    delete:
      operationId: deleteDocument
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: empty
  /documents/{id}/assistants:
    post:
      operationId: createAssistant
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        201:
          description: return empty
          schema:
            type: object
            additionalProperties: false
  /documents/{id}/messages:
    get:
      operationId: getMessages
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: return messages
          schema:
            type: array
            items:
              $ref: "#/definitions/Message"
    post:
      operationId: createMessage
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: message
          in: formData
          required: true
          type: string
      responses:
        201:
          description: return empty
          schema:
            type: object
            additionalProperties: false
  /documents/pre_signed_upload_url:
    post:
      operationId: documentPreSignedUploadUrl
      responses:
        200:
          description: empty
          schema:
            type: object
            properties:
              url:
                type: string
              key:
                type: string
            required:
              - url
              - key
  /documents/pre_signed_get_url:
    post:
      operationId: documentPreSignedGetUrl
      responses:
        200:
          description: empty
          schema:
            type: object
            properties:
              url:
                type: string
            required:
              - url

definitions:
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
    required:
      - id
      - name
      - created_at
      - updated_at
  Document:
    type: object
    properties:
      id:
        type: string
      user_id:
        type: string
      name:
        type: string
      description:
        type: string
      gs_file_url:
        type: string
      status:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
    required:
      - id
      - user_id
      - name
      - description
      - gs_file_url
      - status
      - created_at
      - updated_at
  Message:
    type: object
    properties:
      id:
        type: string
      thread_id:
        type: string
      role:
        type: string
      message:
        type: string
      created_at:
        type: string
    required:
      - id
      - thread_id
      - role
      - message
      - created_at