swagger: "2.0"
info:
  title: PDF Assistant API
  version: "1.0.0"
host: "api-gateway-a55kw77s.an.gateway.dev"
schemes:
  - "https"
produces:
  - "application/json"
basePath: "/"

x-google-backend:
  address: https://pdf-assistant-api-794862978184.asia-northeast1.run.app
  path_translation: APPEND_PATH_TO_ADDRESS

securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://dev-im6sd3gmyj703h6n.us.auth0.com/"
    x-google-jwks_uri: "https://dev-im6sd3gmyj703h6n.us.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://api-gateway-a55kw77s.an.gateway.dev"
security:
  - auth0_jwk: []

paths:
  /hello:
    post:
      operationId: postHello
      responses:
        200:
          description: Response...
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message