swagger: "2.0"
info:
  title: PDF Assistant API
  version: "1.0.0"
host: "api-gateway-a55kw77s.an.gateway.dev"
schemes:
  - "https"
basePath: "/"
paths:
  /hello:
    post:
      operationId: postHello
      x-google-backend:
        address: https://pdf-assistant-api-794862978184.asia-northeast1.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      produces:
        - "application/json"
      responses:
        200:
          description: Response...
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message